import { type Config } from "tailwindcss";

export default {
  darkMode: "media",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {},
  },
  daisyui: {
    themes: [
      {
        light: {
          "primary": "#4c4f69",
          "secondary": "#5c5f77",
          "accent": "#6c6f85",
          "neutral": "#ccd0da",
          "base-100": "#eff1f1",
          "info": "#1e66f5",
          "success": "#40a02b",
          "warning": "#df8e1d",
          "error": "#d20f39",
        },
        dark: {
          "primary": "#c6d0f5",
          "secondary": "#b5bfe2",
          "accent": "#a5adce",
          "neutral": "#292c3c",
          "base-100": "#303446",
          "info": "#8caaee",
          "success": "#a6d189",
          "warning": "#e5c890",
          "error": "#e78284",
        },
        darkCyber: {
          "primary": "#0062ff",
          "primary-content": "#d0e3ff",
          "secondary": "#00d5ac",
          "secondary-content": "#00100b",
          "accent": "#00bda0",
          "accent-content": "#000d09",
          "neutral": "#232a2a",
          "neutral-content": "#ced0d0",
          "base-100": "#202d3a",
          "base-200": "#1a2631",
          "base-300": "#151f28",
          "base-content": "#cdd1d4",
          "info": "#0093fc",
          "info-content": "#000816",
          "success": "#00c779",
          "success-content": "#000e05",
          "warning": "#a37700",
          "warning-content": "#0a0500",
          "error": "#e94458",
          "error-content": "#130203",
        }
      },
      "nord",
      "black",
      "lofi",
      "retro",
      "night",
      "cyberpunk",
      "aqua",
      "valentine",
      "pastel",
    ],
  },
  plugins: [require('daisyui')],
} satisfies Config;
